### ISSUE TITLE
 IconFont 全量使用注册异常，导致无法使用

### ISSUE THREAD

**Issue by wypbin** [jdf2e/nutui-icons#1]
vite4.0

import { IconFont } from '@nutui/icons-vue'
app.use(IconFont)

提示如下
![image](https://user-images.githubusercontent.com/48672496/212691510-216a2e4c-5ece-4a43-9fd2-482d6886a069.png)
![image](https://user-images.githubusercontent.com/48672496/212691660-150746f0-439c-4303-9a66-4c15148b31b3.png)

**Comment by remxcode** [comment]
+1，遇到相同问题

**Comment by richard1015** [comment]
暂时采用 , 下个版本修复
```
app.component('IconFont',IconFont);
```

**Comment by eiinu** [comment]
`@nutui/icons-vue@0.0.26`
