### ISSUE TITLE
IconFont或者直接引入图标，均无法显示

### ISSUE THREAD

**Issue by themusecatcher** [jdf2e/nutui-icons#22]
开发所使用的主要依赖如下:
taro@3.6.26
vue@3.4.21
@nutui/nutui-taro@4.3.6
@nutui/icons-vue-taro@0.0.9
webpack@5.91.0
如下图所示，在微信开发者工具里，启动项目pnpm dev:weapp 图标均没有显示出来，无论使用<IconFont />亦或是 直接引入图标
<img width="1053" alt="image" src="https://github.com/jdf2e/nutui-icons/assets/46012811/65d0253a-9fe5-46d3-8c6b-1dac0f4041d4">

**Comment by eiinu** [comment]
https://github.com/jdf2e/nutui/issues/2138

**Comment by themusecatcher** [comment]
🐂🍺
